
[[service]]
name = "all-urls"
k8s_service = "all-urls"
hostname = "all-urls.example.com"

[[service]]
name = "custom-url"
k8s_service = "custom-url"
hostname = "custom-url.example.com"

  [[service.route]]
  url = "/path/foo/"
  k8s_service = "custom-url"
