
FROM golang:1.8
MAINTAINER Ernesto Alejo <ernesto@altiplaconsulting.com>

# Glide
RUN curl -L -S -o glide.tar.gz https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz && \
    tar -xzf glide.tar.gz && \
    mv linux-amd64/glide /usr/bin/glide && \
    rm -r linux-amd64

# UID & GID inside the container
ARG USR_ID=0
ARG GRP_ID=0
RUN groupadd --gid $GRP_ID -r local -o && \
    useradd --system --uid=$USR_ID --gid=$GRP_ID --home-dir /home/local local -o && \
    mkdir /home/local && \
    chown local:local /home/local && \
    chown -R local:local /go

RUN go get github.com/skelterjohn/rerun

ENV GLIDE_HOME /tmp
ENV HOME /home/local

USER local
WORKDIR /go/src/baster
CMD rerun baster
