
apiVersion: v1
kind: Service
metadata:
  name: baster
spec:
  selector:
    app: baster
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: LoadBalancer
  loadBalancerIP: 1.2.3.4
